### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by lassemt** [Spark-AR-Community/awesome-sparkar#1]
I think it can be good to start with the structure of our awesome list. Choosing categories we will make it easier to find resources.

My suggestions:

- [x] Official Spark AR Pages
- [x] 3rd-party wikis and documentation
- [x] Tutorials and examples
- [x] Open source patches
- [x] Snippets
- [x] Gumroad sellers
- [x] Other relevant resources (blender etc.)

**Comment by lassemt** [comment]
Here is my proposed table of content:
1. Official documentation and links
2. Patches
2a. Free patches
2b. Paid patches
3. Scripts
4. Example Projects
5. Tutorials
5a. Videos
5b. Articles
5c. Streams
6. Miscellaneous resources and collections (Such as Billy's Spark AR TV, and the wiki pages)

@recursiveIceCreamEater @hongweitang What do you guys think?

**Comment by tomaspietravallo** [comment]
Yes! Though I eventually if we get a lot of patches maybe having them subdivided into groups could be really helpful, same with scripts. Eg:

2. Free patches
2.1 SDFs
2.2 3d related
2.3 Image retouching

(Fomated as 2.n and not 2.1.n because I can't figure out how to make GitHub markdown display it properly)

**Comment by lassemt** [comment]
> 1. Free patches
>    2.1 SDFs
>    2.2 3d related
>    2.3 Image retouching

This might get to nested? I think following the requirement _"Entries have a description unless the title is descriptive enough by itself."_ is the key. So we have to make it clear what the Patch does instead of categorizing them too much.

**Comment by hongweitang** [comment]
> Here is my proposed table of content:
> 
> 1. Official documentation and links
> 2. Patches
>    2a. Free patches
>    2b. Paid patches
> 3. Scripts
> 4. Example Projects
> 5. Tutorials
>    5a. Videos
>    5b. Articles
>    5c. Streams
> 6. Miscellaneous resources and collections (Such as Billy's Spark AR TV, and the wiki pages)
> 
> @recursiveIceCreamEater @hongweitang What do you guys think?

Markdown isn't really great for sub numbered lists (stronghold of tools such as LaText).
Yeah I like that list. I wonder if tutorial section is more relevant than resources to download? The focus can be on education first?

> Free patches
> 2.1 SDFs
> 2.2 3d related
> 2.3 Image retouching

For the beginning it doesn't need to be this specific list of free patches. We can explain the content for the beginning. The categories here are quite specific.

**Comment by tomaspietravallo** [comment]
Yeah, in any case, there aren't that many patches, you could just read all the titles in a minute. But as you said:

> the requirement "Entries have a description unless the title is descriptive enough by itself." is the key

**Comment by lassemt** [comment]
> I wonder if tutorial section is more relevant than resources to download? The focus can be on education first?

Yeah, maybe this should go up on the 2nd place, and be named "Learning"? Same with "Example projects" before patches and scripts maybe? 

> For the beginning it doesn't need to be this specific list of free patches. We can explain the content for the beginning. The categories here are quite specific.
I agree. I also think we can make subcategories later if the list gets super big.

So the current proposal now is (numbers is just for order, and not needed in final ToC):
1. Official documentation and links
2. Tutorials/Learning
2a. Videos
2b. Articles
2c. Streams
3. Example Projects
4. Patches
4a. Free patches
4b. Paid patches
5. Scripts
6. Miscellaneous resources and collections (Such as Billy's Spark AR TV, and the wiki pages)

**Comment by tomaspietravallo** [comment]
> Yeah, maybe this should go up on the 2nd place, and be named "Learning"? Same with "Example projects" before patches and scripts maybe?

I agree, I'd rather have a learning section at the top, it'd be more friendly to beginners, who may not even know how to use GitHub (I myself only started a few months ago). I like the current proposal.
My question regarding patches now is the following: What to do with profiles/repositories with multiple things? Shall we get the links to every individual repo/folder and link them?

**Comment by lassemt** [comment]
@recursiveIceCreamEater @hongweitang I've created a new repo for this in the branch awesome-spark-ar/structure-v2. 

As you see we have a bit of a job writing descriptions for the content, but I think it's a good idea that we should not add links without titles and descriptions into that branch so we keep it clean from the start before we merge it into master. 

> My question regarding patches now is the following: What to do with profiles/repositories with multiple things? Shall we get the links to every individual repo/folder and link them?

Yes, I think that is the best. Take the latest stuff that we know is working with the  4-5 latest versions of Spark AR. We don't have to add all of it, but maybe the popular ones we get enough to have a good example of how things should be added. Then people can add their own title, description, and links in the future. We also need an contributing.md, I'll create an issue for that ASAP.

**Comment by hongweitang** [comment]
Yeah contributing.md will be great for that.

Exactly we should reduce it to relevant content or if its on youtube we can copy the link to playlists which are working as a series of lectures.

What you guys think about content like that? https://www.instagram.com/p/CBCZjsfjmsO/
Should that be added as some form of "Quick Tips" under tutorials?

**Comment by lassemt** [comment]
Yeah, I think YouTube playlists should be fine, but channels are very different. Playlists can go under videos e.g. [TITLE OF PLAYLIST IF IT'S CLEAR]/(LINK) - DESCRIPTION OF SERIES. Maybe a rule can be that we only add playlists on a specific topic, such as Sohail's latest Scripting and Shaders? 

> What you guys think about content like that? https://www.instagram.com/p/CBCZjsfjmsO/
> Should that be added as some form of "Quick Tips" under tutorials?

I think maybe Quick Tips / Tips and Tricks can be a top category as it's often different from a full tutorial.

**Comment by lassemt** [comment]
Closing this issue as it looks like we have it well structured now.
