### ISSUE TITLE
Styling and consistency regarding names

### ISSUE THREAD

**Issue by tomaspietravallo** [Spark-AR-Community/awesome-sparkar#5]
When writing the names of the name of patches/scripts/videos, taking the name of the repo/video seems like the obvious choice, but as seen in the image below, there's quickly a cascade of "spark"
<img width="703" alt="Screen Shot 2020-06-05 at 13 13 31" src="https://user-images.githubusercontent.com/62444821/83899634-29836580-a72f-11ea-812f-792cf796b046.png">
What should be done? Should the spark/sparkar at the beginning be removed or left? And also, should the names be capitalised? I know this sound like an OCD thing, but it isn't, I just think starting right from the beginning will end up being less work.

Not relevant to the issue but in case anyone is wondering I decided to change my username to @tomaspietravallo (real name) instead of the former, so that it is the same as it is on Facebook, and it becomes easier to identify across the platforms

**Comment by lassemt** [comment]
I think we should do [title case format](https://capitalizemytitle.com/) all the time as that will make everything look neutral. Regarding the Spark prefix, I think you can remove that. I removed that from the titles in the few examples I added in the new branch.

I recognized the names from the mail notifications! Thank you for contributing, Tomas! 🙌🏼
