### ISSUE TITLE
Status v2 before merging

### ISSUE THREAD

**Issue by lassemt** [Spark-AR-Community/awesome-sparkar#9]
Hi friends, 

I was thinking is there something we need from the old list before merging structured-v2 into master? I think we should do this ASAP and make clear contributing guidelines, such as don't link to youtube accounts, but playlists or specific tutorials. Projects should be hosted on Github. etc. Then we can post this in the FB group to get people to contribute.

What do you guys think? @tomaspietravallo @hongweitang

**Comment by lassemt** [comment]
Also, I noticed that for playlists for video tutorials. It is awesome when the playlist is on a specific subject within Spark rather than a collection of all the tutorials. Should we take that as a requirement for playlists, that they have to be about a specific subject?

**Comment by tomaspietravallo** [comment]
I think the only thing left from the old list is are gumroad & paid patches. About the playlists, it'd be nice to have all the playlists divided up, that's true

Edit: are we going to add the 3rd party wikis and aggregator?

**Comment by lassemt** [comment]
@tomaspietravallo I've already added som on the "Other Resources" section. I also got Josh to make a playlist for his LUT's, so I've updated that. Also the contribution file with info on sharing projects and videos

**Comment by hongweitang** [comment]
Yes love the new direction of the structure and how the content has to be prepared. 

The contribution guidelines are gonna be crucial for how that will continue. Clear explanations of the contributed links make it more searchable and findable through the internet too.

**Comment by lassemt** [comment]
Merged.
